title: Naren Ramesh
logo: /assets/img/naren_logo_2.jpeg
description: The projects and ideas of Naren Ramesh; undergraduate student at the University of Toronto.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
